const GLIMMER_DATA = {
  generatedAt: "2026-08-30",
  entities: [
    {
      id: "tt-a1i/archify",
      owner: "tt-a1i",
      name: "archify",
      kind: "repository",
      description: "Agent skill for beautiful, verifiable architecture, workflow, sequence, data-flow, and lifecycle diagrams.",
      url: "https://github.com/tt-a1i/archify",
      stars: 15700,
      starsGainedWeek: 699,
      starsGainedMonth: 22600,
      language: "JavaScript",
      license: "MIT",
      topics: ["AI agent", "AI skills"],
      momentum: "rising",
      status: "New 2026",
      sources: [{ name: "GitHub", url: "https://github.com/tt-a1i/archify" }],
      briefing: {
        editorialHeadline: "Archify turns agent-generated diagrams into verifiable engineering artifacts.",
        whatItDoes: "Turns text prompts into self-contained HTML diagrams with motion and crisp export. Aimed at engineering teams that need verifiable visual docs.",
        whyTrending: "It hit #1 on the Trendshift weekly list as interest in AI-generated system design visuals spiked. The README includes live examples.",
        recentChanges: [{ type: "release", title: "v0.2.0", summary: "Adds sequence and lifecycle diagram types.", url: "https://github.com/tt-a1i/archify/releases/tag/v0.2.0" }],
        signals: { activity: 72, releaseCadence: 60, contributorGrowth: 45, issueResolution: 50 },
        alternatives: [{ name: "Mermaid", url: "https://github.com/mermaid-js/mermaid" }, { name: "draw.io", url: "https://github.com/jgraph/drawio" }]
      },
      mentions: [{ source: "Trendshift", url: "https://trendshift.io/weekly", quote: "#1 weekly trending repository for AI agent and AI skills." }],
      activity: [120, 145, 180, 220, 310, 450, 699]
    },
    {
      id: "freestylefly/awesome-gpt-image-2",
      owner: "freestylefly",
      name: "awesome-gpt-image-2",
      kind: "repository",
      description: "Prompt as Code: an industrial prompt engine and template library for GPT-Image2.",
      url: "https://github.com/freestylefly/awesome-gpt-image-2",
      stars: 12400,
      starsGainedWeek: 986,
      starsGainedMonth: 16000,
      language: "Markdown",
      license: "MIT",
      topics: ["AI image generation", "Curated list"],
      momentum: "rising",
      status: "New 2026",
      sources: [{ name: "GitHub", url: "https://github.com/freestylefly/awesome-gpt-image-2" }],
      briefing: {
        editorialHeadline: "Prompt-as-code is becoming a production workflow for image teams.",
        whatItDoes: "A curated collection of 530+ reverse-engineered GPT-Image2 examples, plus industrial prompt templates.",
        whyTrending: "It captures the wave of builders trying to control image generation through prompt engineering. High save and share intent.",
        recentChanges: [{ type: "commit", title: "530 examples", summary: "Added the 500+ case reverse-engineering section.", url: "https://github.com/freestylefly/awesome-gpt-image-2/commit/def456" }],
        signals: { activity: 68, releaseCadence: 30, contributorGrowth: 80, issueResolution: 40 },
        alternatives: [{ name: "Midjourney prompts", url: "https://github.com/willwulfken/MidJourney-Styles-and-Keywords-Reference" }]
      },
      mentions: [{ source: "Trendshift", url: "https://trendshift.io/weekly", quote: "#2 weekly gainer in AI image generation." }],
      activity: [80, 120, 200, 350, 520, 800, 986]
    },
    {
      id: "bilawalsidhu/gods-eye-view",
      owner: "bilawalsidhu",
      name: "gods-eye-view",
      kind: "repository",
      description: "God's Eye View v1 public open-source release placeholder.",
      url: "https://github.com/bilawalsidhu/gods-eye-view",
      stars: 11800,
      starsGainedWeek: 2200,
      starsGainedMonth: 12000,
      language: "TypeScript",
      license: "MIT",
      topics: ["AI agent"],
      momentum: "rising",
      status: "New 2026",
      sources: [{ name: "GitHub", url: "https://github.com/bilawalsidhu/gods-eye-view" }],
      briefing: {
        editorialHeadline: "God's Eye View is an audience spike waiting for product evidence.",
        whatItDoes: "A placeholder for a coming AI agent project. The repo itself is mostly documentation and teaser content.",
        whyTrending: "The star velocity is high because the founder has a large audience. Treat this as audience-driven, not yet usage-driven.",
        recentChanges: [{ type: "commit", title: "Initial public release", summary: "Placeholder README and roadmap.", url: "https://github.com/bilawalsidhu/gods-eye-view/commit/ghi789" }],
        signals: { activity: 90, releaseCadence: 20, contributorGrowth: 95, issueResolution: 30 },
        alternatives: []
      },
      mentions: [{ source: "X", url: "https://x.com/bilawalsidhu", quote: "Announcing the open-source release of God's Eye View." }],
      activity: [500, 900, 1200, 1500, 1800, 2100, 2200]
    },
    {
      id: "MadsLorentzen/ai-job-search",
      owner: "MadsLorentzen",
      name: "ai-job-search",
      kind: "repository",
      description: "The job search that runs on your machine. AI job application framework built on Claude Code.",
      url: "https://github.com/MadsLorentzen/ai-job-search",
      stars: 4900,
      starsGainedWeek: 1200,
      starsGainedMonth: 4900,
      language: "Python",
      license: "MIT",
      topics: ["AI agent", "AI workflow", "Workflow automation", "Resume building"],
      momentum: "rising",
      status: "New 2026",
      sources: [{ name: "GitHub", url: "https://github.com/MadsLorentzen/ai-job-search" }],
      briefing: {
        editorialHeadline: "Local job-search agents are winning by owning the whole workflow.",
        whatItDoes: "Evaluates job postings, tailors CVs, writes cover letters, and preps interviews using a local AI agent.",
        whyTrending: "It taps into the post-layoff, AI-copilot job search trend. The README is a clear tutorial, which drives saves and forks.",
        recentChanges: [{ type: "release", title: "v0.1.0", summary: "Initial Claude Code integration for job posting analysis.", url: "https://github.com/MadsLorentzen/ai-job-search/releases/tag/v0.1.0" }],
        signals: { activity: 75, releaseCadence: 55, contributorGrowth: 60, issueResolution: 65 },
        alternatives: [{ name: "AutoApply", url: "https://github.com/some/autoapply" }]
      },
      mentions: [{ source: "Hacker News", url: "https://news.ycombinator.com/item?id=49495000", quote: "Show HN: An AI agent that runs my entire job search locally." }],
      activity: [100, 250, 400, 600, 850, 1000, 1200]
    },
    {
      id: "GetBusbar/busbar",
      owner: "GetBusbar",
      name: "busbar",
      kind: "repository",
      description: "Control what AI can do before it acts.",
      url: "https://github.com/GetBusbar/busbar",
      website: "https://getbusbar.com",
      stars: 3500,
      starsGainedWeek: 800,
      starsGainedMonth: 12000,
      language: "TypeScript",
      license: "Apache-2.0",
      topics: ["AI agent", "AI infrastructure"],
      momentum: "rising",
      status: "New 2026",
      sources: [{ name: "GitHub", url: "https://github.com/GetBusbar/busbar" }, { name: "Product Hunt", url: "https://www.producthunt.com/posts/busbar" }],
      briefing: {
        editorialHeadline: "Agent permissions are becoming infrastructure, not a safety add-on.",
        whatItDoes: "A permissions layer for AI agents. Define what tools an agent can call and what data it can access before execution.",
        whyTrending: "Featured by Trendshift and tied to the growing conversation around AI safety and agent governance. Also a Product Hunt launch.",
        recentChanges: [{ type: "release", title: "v0.4.0", summary: "Introduced policy-as-code rules.", url: "https://github.com/GetBusbar/busbar/releases/tag/v0.4.0" }],
        signals: { activity: 70, releaseCadence: 70, contributorGrowth: 55, issueResolution: 75 },
        alternatives: [{ name: "LangChain LangServe", url: "https://github.com/langchain-ai/langserve" }]
      },
      mentions: [{ source: "Product Hunt", url: "https://www.producthunt.com/posts/busbar", quote: "Busbar: control what AI can do before it acts." }],
      activity: [150, 300, 450, 550, 650, 750, 800]
    },
    {
      id: "deepseek-ai/deepseek-harness",
      owner: "deepseek-ai",
      name: "deepseek-harness",
      kind: "repository",
      description: "Harness for running and evaluating DeepSeek models.",
      url: "https://github.com/deepseek-ai/deepseek-harness",
      stars: 155000,
      starsGainedWeek: 2500,
      starsGainedMonth: 23700,
      language: "Python",
      license: "Apache-2.0",
      topics: ["AI agent"],
      momentum: "steady",
      status: "New 2026",
      sources: [{ name: "GitHub", url: "https://github.com/deepseek-ai/deepseek-harness" }],
      briefing: {
        editorialHeadline: "DeepSeek Harness is rising because everything can become a plugin.",
        whatItDoes: "A model evaluation and inference harness for the DeepSeek family. Used for benchmarks and reproducible runs.",
        whyTrending: "The repo is large because of the DeepSeek brand. New stars this week are driven by the latest model release.",
        recentChanges: [{ type: "release", title: "v1.1.0", summary: "Added support for the new reasoning model.", url: "https://github.com/deepseek-ai/deepseek-harness/releases/tag/v1.1.0" }],
        signals: { activity: 85, releaseCadence: 80, contributorGrowth: 70, issueResolution: 80 },
        alternatives: [{ name: "lm-evaluation-harness", url: "https://github.com/EleutherAI/lm-evaluation-harness" }]
      },
      mentions: [{ source: "Hacker News", url: "https://news.ycombinator.com/item?id=49496000", quote: "DeepSeek release thread." }],
      activity: [1800, 1900, 2050, 2200, 2300, 2400, 2500]
    },
    {
      id: "DietrichGebert/ponytail",
      owner: "DietrichGebert",
      name: "ponytail",
      kind: "repository",
      description: "Makes your AI agent think like the laziest senior dev in the room.",
      url: "https://github.com/DietrichGebert/ponytail",
      stars: 7600,
      starsGainedWeek: 326,
      starsGainedMonth: 23300,
      language: "TypeScript",
      license: "MIT",
      topics: ["AI agent", "AI coding assistant"],
      momentum: "steady",
      status: "New 2026",
      sources: [{ name: "GitHub", url: "https://github.com/DietrichGebert/ponytail" }],
      briefing: {
        editorialHeadline: "Developers want coding agents that know when not to write code.",
        whatItDoes: "A set of prompts and tools that nudge coding agents toward minimal, high-quality changes.",
        whyTrending: "It resonates with developers tired of agents that over-engineer. The README is opinionated and memorable.",
        recentChanges: [{ type: "commit", title: "Lazy prompts", summary: "Adds the core lazy-senior-dev prompt pack.", url: "https://github.com/DietrichGebert/ponytail/commit/jkl012" }],
        signals: { activity: 55, releaseCadence: 40, contributorGrowth: 50, issueResolution: 60 },
        alternatives: [{ name: "anthropics/skills", url: "https://github.com/anthropics/skills" }]
      },
      mentions: [{ source: "X", url: "https://x.com/DietrichGebert/status/209390000", quote: "The best code is the code you never wrote." }],
      activity: [120, 150, 180, 220, 260, 300, 326]
    },
    {
      id: "FlashML-org/FreeToken",
      owner: "FlashML-org",
      name: "FreeToken",
      kind: "repository",
      description: "Free token routing for LLM API calls.",
      url: "https://github.com/FlashML-org/FreeToken",
      stars: 6300,
      starsGainedWeek: 541,
      starsGainedMonth: 6300,
      language: "Python",
      license: "MIT",
      topics: ["AI infrastructure", "Local LLM"],
      momentum: "rising",
      status: "New 2026",
      sources: [{ name: "GitHub", url: "https://github.com/FlashML-org/FreeToken" }],
      briefing: {
        editorialHeadline: "LLM cost anxiety is creating a new routing layer.",
        whatItDoes: "Routes LLM calls across free tiers and trial credits so hobby projects can stay under budget.",
        whyTrending: "Cost anxiety around LLM APIs is real. The project solves it with a clear value prop.",
        recentChanges: [{ type: "release", title: "v0.1.0", summary: "First public release with OpenAI and Groq adapters.", url: "https://github.com/FlashML-org/FreeToken/releases/tag/v0.1.0" }],
        signals: { activity: 65, releaseCadence: 50, contributorGrowth: 75, issueResolution: 55 },
        alternatives: [{ name: "LiteLLM", url: "https://github.com/BerriAI/litellm" }]
      },
      mentions: [{ source: "Reddit", url: "https://reddit.com/r/LocalLLaMA/comments/xyz123", quote: "Has anyone tried FreeToken for API rotation?" }],
      activity: [50, 120, 200, 300, 400, 480, 541]
    },
    {
      id: "calesthio/OpenMontage",
      owner: "calesthio",
      name: "OpenMontage",
      kind: "repository",
      description: "Open-source, agentic video production system with 12 production pipelines.",
      url: "https://github.com/calesthio/OpenMontage",
      stars: 4200,
      starsGainedWeek: 413,
      starsGainedMonth: 4200,
      language: "Python",
      license: "MIT",
      topics: ["AI agent", "AI video generation", "Workflow automation"],
      momentum: "rising",
      status: "New 2026",
      sources: [{ name: "GitHub", url: "https://github.com/calesthio/OpenMontage" }],
      briefing: {
        editorialHeadline: "Agentic video tools are shifting from demos to repeatable pipelines.",
        whatItDoes: "Lets a coding agent produce videos through 12 predefined pipelines and 100+ tools.",
        whyTrending: "It sits at the intersection of AI video and agentic workflows. The README demos are shareable.",
        recentChanges: [{ type: "commit", title: "12 pipelines", summary: "Added the full production pipeline suite.", url: "https://github.com/calesthio/OpenMontage/commit/mno345" }],
        signals: { activity: 60, releaseCadence: 45, contributorGrowth: 70, issueResolution: 50 },
        alternatives: [{ name: "Runway", url: "https://runwayml.com" }]
      },
      mentions: [{ source: "Hacker News", url: "https://news.ycombinator.com/item?id=49497000", quote: "Show HN: I taught my agent to make videos." }],
      activity: [40, 100, 180, 250, 320, 380, 413]
    },
    {
      id: "K-Dense-AI/scientific-agent-skills",
      owner: "K-Dense-AI",
      name: "scientific-agent-skills",
      kind: "repository",
      description: "Turn any AI agent into an AI Scientist.",
      url: "https://github.com/K-Dense-AI/scientific-agent-skills",
      stars: 3700,
      starsGainedWeek: 181,
      starsGainedMonth: 3700,
      language: "Python",
      license: "MIT",
      topics: ["AI agent", "AI skills"],
      momentum: "rising",
      status: "New 2026",
      sources: [{ name: "GitHub", url: "https://github.com/K-Dense-AI/scientific-agent-skills" }],
      briefing: {
        editorialHeadline: "Scientific agent skills are finding a focused early audience.",
        whatItDoes: "A library of 163 ready-to-use scientific skills plus database connectors for biology, chemistry, medicine, and drug discovery.",
        whyTrending: "Academic and biotech users are adopting agentic research tools. The repo is niche but has high save intent.",
        recentChanges: [{ type: "commit", title: "163 skills", summary: "Expanded validated skill set for drug discovery.", url: "https://github.com/K-Dense-AI/scientific-agent-skills/commit/pqr678" }],
        signals: { activity: 50, releaseCadence: 35, contributorGrowth: 40, issueResolution: 60 },
        alternatives: [{ name: "Sakana AI", url: "https://sakana.ai" }]
      },
      mentions: [{ source: "Reddit", url: "https://reddit.com/r/bioinformatics/comments/abc456", quote: "Has anyone used this for literature review?" }],
      activity: [30, 60, 90, 120, 150, 170, 181]
    },
    {
      id: "basecamp/omarchy",
      owner: "basecamp",
      name: "omarchy",
      kind: "repository",
      description: "Beautiful, Modern & Opinionated Linux.",
      url: "https://github.com/basecamp/omarchy",
      website: "https://omarchy.com",
      stars: 5700,
      starsGainedWeek: 526,
      starsGainedMonth: 10500,
      language: "Shell",
      license: "MIT",
      topics: ["Self-hosted"],
      momentum: "rising",
      status: null,
      sources: [{ name: "GitHub", url: "https://github.com/basecamp/omarchy" }],
      briefing: {
        editorialHeadline: "Omarchy is turning a Linux distribution into a developer lifestyle product.",
        whatItDoes: "A Linux distribution tailored for developer workstations, with strong conventions and defaults.",
        whyTrending: "Basecamp's audience and a string of Omarchy-related launches are driving attention. It is more lifestyle OS than enterprise play.",
        recentChanges: [{ type: "commit", title: "Installer update", summary: "Improved first-boot experience.", url: "https://github.com/basecamp/omarchy/commit/stu901" }],
        signals: { activity: 65, releaseCadence: 55, contributorGrowth: 60, issueResolution: 70 },
        alternatives: [{ name: "Fedora Silverblue", url: "https://fedoraproject.org/atomic-desktops/" }]
      },
      mentions: [{ source: "X", url: "https://x.com/dhh/status/209400000", quote: "Omarchy is the malleable OS." }],
      activity: [100, 200, 300, 380, 450, 500, 526]
    },
    {
      id: "tailscale/tailcat",
      owner: "tailscale",
      name: "tailcat",
      kind: "repository",
      description: "like netcat, but over Tailscale's data plane, without Tailscale's control plane.",
      url: "https://github.com/tailscale/tailcat",
      stars: 3400,
      starsGainedWeek: 84,
      starsGainedMonth: 3400,
      language: "Go",
      license: "BSD-3-Clause",
      topics: ["Self-hosted"],
      momentum: "steady",
      status: null,
      sources: [{ name: "GitHub", url: "https://github.com/tailscale/tailcat" }],
      briefing: {
        editorialHeadline: "Tailcat gives self-hosters a smaller way into the Tailscale data plane.",
        whatItDoes: "A networking tool for sending packets over Tailscale's mesh network without the central control plane.",
        whyTrending: "It appeals to self-hosters and network engineers. Tailscale's brand gives it credibility.",
        recentChanges: [{ type: "release", title: "v0.0.1", summary: "Initial release.", url: "https://github.com/tailscale/tailcat/releases/tag/v0.0.1" }],
        signals: { activity: 45, releaseCadence: 60, contributorGrowth: 35, issueResolution: 85 },
        alternatives: [{ name: "netcat", url: "https://en.wikipedia.org/wiki/Netcat" }]
      },
      mentions: [{ source: "Hacker News", url: "https://news.ycombinator.com/item?id=49498000", quote: "Tailscale open sourced a neat netcat alternative." }],
      activity: [10, 20, 35, 50, 65, 78, 84]
    }
  ]
};
